In [31]:
import tqdm as notebook_tqdm
from tqdm import tqdm

# for data
import json
import pandas as pd
import numpy as np
import csv

In [42]:
# hadits_list = ['bukhari']
hadits_list = ['abudaud', 'darimi', 'ibnumajah', 'malik', 'muslim', 'nasai', 'tirmidzi']

In [55]:
hadits_loc= 'Dataset/bert_result/model4/ns/'
# hadits_save = 'website/data/ns/'
hadits_save = 'Dataset/bert_result/model4/log_ns/'
# hadits_loc= 'Dataset/svm_nb_result/log_ns/'
# hadits_save = 'Dataset/svm_nb_result/log_ns/'

In [13]:
hadits = pd.read_csv('Dataset/bert_result/model4/ns/abudaud.csv')
hadits.head()

,haditsId,kitabId,indo,arab,label
0,1,1,Telah menceritakan kepada kami [Abdullah bin M...,حَدَّثَنَا عَبْدُ اللَّهِ بْنُ مَسْلَمَةَ بْنِ...,28
1,2,1,Telah menceritakan kepada kami [Musaddad bin M...,حَدَّثَنَا مُسَدَّدُ بْنُ مُسَرْهَدٍ حَدَّثَنَ...,26
2,3,1,Telah menceritakan kepada kami [Musa bin Isma'...,حَدَّثَنَا مُوسَى بْنُ إِسْمَعِيلَ حَدَّثَنَا ...,3
3,4,1,Telah menceritakan kepada kami [Musaddad bin M...,حَدَّثَنَا مُسَدَّدُ بْنُ مُسَرْهَدٍ حَدَّثَنَ...,44
4,5,1,Telah menceritakan kepada kami [Amru bin Marzu...,حَدَّثَنَا عَمْرُو بْنُ مَرْزُوقٍ أَخْبَرَنَا ...,3

In [29]:
for i in hadits_list:
    new_loc = hadits_loc + str(i) + '.csv'
    hadits = pd.read_csv(new_loc)
    for j in tqdm(range(0, 77)):
        temp = hadits[hadits['kitabId']== j]
        save = hadits_save + str(i) + '/' + str(j) + '.csv'
        temp.to_csv(save, index=False)

100%|█████████████████████████████████████████████████████████████████████████████████| 77/77 [00:00<00:00, 245.29it/s]

In [56]:
for i in hadits_list:
    final = pd.DataFrame()
    new_loc = hadits_loc + str(i) + '.csv'
    hadits = pd.read_csv(new_loc)
    result = hadits.groupby('label').describe()
    final[i] = result['haditsId']['count']
    file_output = hadits_save + str(i) + '.csv'
    result.to_csv(file_output, index= True)

In [58]:
hadits = pd.read_csv(file_output)
hadits

,Unnamed: 0,haditsId,haditsId.1,haditsId.2,haditsId.3,haditsId.4,haditsId.5,haditsId.6,haditsId.7,kitabId,kitabId.1,kitabId.2,kitabId.3,kitabId.4,kitabId.5,kitabId.6,kitabId.7
0,NaN,count,mean,std,min,25%,50%,75%,max,count,mean,std,min,25%,50%,75%,max
1,label,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,1.0,3567.0,NaN,3567.0,3567.0,3567.0,3567.0,3567.0,1.0,49.0,NaN,49.0,49.0,49.0,49.0,49.0
3,1,44.0,2437.318181818182,577.6295091962422,1082.0,2089.5,2432.0,2552.25,3870.0,44.0,36.38636363636363,8.37553444068013,9.0,32.75,37.0,40.0,49.0
4,2,24.0,2699.0833333333335,741.8221348208375,883.0,2535.75,2587.0,3109.75,3766.0,24.0,39.708333333333336,11.566364904387605,6.0,39.25,41.0,47.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,72,23.0,2545.1304347826085,1000.3070121603042,559.0,2102.5,2533.0,3370.5,3871.0,23.0,35.95652173913044,15.15219234323285,3.0,33.0,40.0,47.5,49.0
73,73,15.0,2335.4,756.5540109130158,1184.0,1830.5,2361.0,3084.0,3335.0,15.0,33.8,13.380155882072954,11.0,27.5,37.0,47.0,48.0
74,74,23.0,1601.2608695652175,1112.8878166689212,31.0,639.0,1450.0,2675.5,3729.0,23.0,21.82608695652174,18.553735654023093,1.0,4.5,20.0,42.5,49.0
75,75,161.0,2664.577639751553,843.7778042807801,207.0,2166.0,2825.0,3277.0,3861.0,161.0,38.732919254658384,12.521859768009282,2.0,33.0,45.0,47.0,49.0
76,76,154.0,2638.525974025974,738.2688476956096,243.0,2325.0,2839.0,3199.5,3890.0,154.0,39.006493506493506,11.865530212846947,2.0,36.0,45.5,47.0,49.0

In [45]:
for i in hadits_list:
    final = pd.DataFrame()
    new_loc = hadits_loc + str(i) + '.csv'
    hadits = pd.read_csv(new_loc)
    final[i] = hadits['haditsId']['count']
    file_output = hadits_save + str(i) + '.csv'
    final.to_csv(file_output, index = False)

KeyError: 'count'